// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBozq5onM70QDu4KvavgkM5KvoYWbSQ7EE',
    appId: '1:874158496423:web:0b1a30905e829321051982',
    messagingSenderId: '874158496423',
    projectId: 'task-manager-7ec9f',
    authDomain: 'task-manager-7ec9f.firebaseapp.com',
    storageBucket: 'task-manager-7ec9f.firebasestorage.app',
    measurementId: 'G-HM245PBR2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnvAcbWZPb_z4WFP6ISd-vHs45f8f2BNo',
    appId: '1:874158496423:android:8fb83224d2092c25051982',
    messagingSenderId: '874158496423',
    projectId: 'task-manager-7ec9f',
    storageBucket: 'task-manager-7ec9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKaId9S8EVynaQe0Kio2BmwPU_pyYte7o',
    appId: '1:874158496423:ios:01f85a51de83a7bf051982',
    messagingSenderId: '874158496423',
    projectId: 'task-manager-7ec9f',
    storageBucket: 'task-manager-7ec9f.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKaId9S8EVynaQe0Kio2BmwPU_pyYte7o',
    appId: '1:874158496423:ios:01f85a51de83a7bf051982',
    messagingSenderId: '874158496423',
    projectId: 'task-manager-7ec9f',
    storageBucket: 'task-manager-7ec9f.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBozq5onM70QDu4KvavgkM5KvoYWbSQ7EE',
    appId: '1:874158496423:web:aa0f000d6c60c4df051982',
    messagingSenderId: '874158496423',
    projectId: 'task-manager-7ec9f',
    authDomain: 'task-manager-7ec9f.firebaseapp.com',
    storageBucket: 'task-manager-7ec9f.firebasestorage.app',
    measurementId: 'G-F59F99JY4H',
  );
}
